version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: app/Dockerfile.backend
    ports:
      - "8000:8000"
    restart: always  # <--- THIS TELLS DOCKER TO START THE CONTAINER ON SYSTEM BOOT

  frontend:
    build:
      context: .
      dockerfile: app/Dockerfile.frontend
    ports:
      - "8501:8501"
    restart: always  # <--- THIS TELLS DOCKER TO START THE CONTAINER ON SYSTEM BOOT
    depends_on:
      - backend